
project_id = "rzrroghnzintpxspwauf"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_signup = true
enable_anonymous_users = false

[auth.email]
enable_signup = true

[db]
port = 54322

[storage]
enabled = true
port = 54325

[edge_functions]
enabled = true
port = 54323

[functions.send-vendor-email]
verify_jwt = false

[functions.create-stripe-checkout]
verify_jwt = true

[functions.verify-stripe-payment]
verify_jwt = true

[functions.create-payment-intent]
verify_jwt = true

[functions.verify-payment-intent]
verify_jwt = true

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false
